### ISSUE TITLE
`mvn` fails to build `qless.lua`

### ISSUE THREAD

**Issue by davidann** [seomoz/qless-java#14]
### Summary:

On initial cloning of this repo, I am unable to build and execute the tests of this repo.

### Settings:
1.  qless-java@d33d864e821bdc9d3abd20ed09f488eb52f6f210
2.  Maven version 3.0.4
3.  Java version 1.7.0_65 (oracle)
4.  OS name: "linux", version: "3.11.0-15-generic", arch: "amd64", family: "unix"

### Repro steps:
1. `git clone git@github.com:seomoz/qless-java.git`
2. `cd qless-java`
3. `git submodule init`
4. `git submodule update`
3. `mvn`

### Expected output:  

All tests pass.

### Actual output: (truncated for brevity)
```
...
  QueueTest.peek:157 » IllegalArgument resource qless.lua not found.
  QueueTest.stats:194 » IllegalArgument resource qless.lua not found.
  QueueTest.heartbeat:106 » IllegalArgument resource qless.lua not found.
  QueueTest.multiPop:133 » IllegalArgument resource qless.lua not found.
  QueueTest.jobsRecur:60 » IllegalArgument resource qless.lua not found.
...
Tests run: 88, Failures: 0, Errors: 81, Skipped: 1
```

### Analysis:

It appears that `qless.lua` is not being built by maven before the tests are run.  `vagrant@dev-all-ubuntu-1204:~/qless-java$ find . -name qless.lua` yields nothing.  But, when I run:

```
vagrant@dev-all-ubuntu-1204:~/qless-java/qless-java/src/qless-core$ make qless.lua
# Cat these files out, but remove all the comments from the source
echo "-- Current SHA: `git rev-parse HEAD`" > qless.lua
echo "-- This is a generated file" >> qless.lua
cat qless-lib.lua api.lua | \
		egrep -v '^[[:space:]]*--[^\[]' | \
		egrep -v '^--$' >> qless.lua
vagrant@dev-all-ubuntu-1204:~/qless-java/qless-java/src/qless-core$ 
```

And then run `mvn`, all the tests pass and `qless.lua` exists:

```
vagrant@dev-all-ubuntu-1204:~/qless-java$ find . -name qless.lua
./qless-java/src/qless-core/qless.lua
./qless-java/target/classes/qless.lua
vagrant@dev-all-ubuntu-1204:~/qless-java$
```

**Comment by b4hand** [comment]
I just did a completely clean checkout and as long as you do the proper submodule initialization, it builds fine even from a clean tree, and that is including generating the `qless.lua` file, so I'm going to call this fixed.
