### ISSUE TITLE
`Client implements Closeable`?

### ISSUE THREAD

**Issue by phs** [seomoz/qless-java#38]
That jedis pool looks like it could use a `close()`...

**Comment by phs** [comment]
Actually, the bundled version of jedis doesn't appear to have a close? (Get a compile error when I try.)

**Comment by davidann** [comment]
@phs I'm running into a similar issue.

I have a long-running process which enqueues jobs:

```java
public void enqueue() {
    	final JedisPool jedisPool = createJedisPoolConfig();
    	final Client client = new com.moz.qless.Client(jedisPool);
        final Queue q = new com.moz.qless.Queue(client, QUEUE_NAME);
        final HashMap<String, Object> data = new HashMap<String, Object>();
        data.put(Shared.TSV_FILENAME_DATA_LABEL, this.fileName);
        data.put(Shared.TSV_HEADERS_DATA_LABEL, this.tsvHeaders);
                
        try {
        	final com.moz.qless.JobSpec jobSpec = new com.moz.qless.JobSpec();
        	jobSpec.setData(data);
            q.put(jobSpec.setKlass(jobs.TSVImporter.class));        
        } catch (IOException e) {
            System.out.println("error is: " + e.toString());
        } finally {
               	jedisPool.close();
        }
    }
```

In this example, I explicitly create a `JedisPool` to give to the `client` and try to `close()` it after the job was `put`.  However, the number of open file descriptors for the redis process grows unbounded.

**Comment by b4hand** [comment]
The interface for `JedisPool` appears to use `returnResource` and not `close`:

https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/JedisPoolAbstract.java

**Comment by b4hand** [comment]
I see at least one leak in this class:

https://github.com/seomoz/qless-java/blob/master/src/main/java/com/moz/qless/Events.java

We call `getResource` in the constructor, but never call `returnResource`.

**Comment by b4hand** [comment]
That appears to be the only leak I can find.

**Comment by b4hand** [comment]
Also, `JedisPool` is an instance of [`Pool`](https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/util/Pool.java) which does appear to be `Closeable`, so the `Pool` itself should probably be closed.

**Comment by b4hand** [comment]
I will say it feels a little skeevy to call `close` on the `JedisPool` when that argument may be passed in via the constructor of [`Client`](https://github.com/seomoz/qless-java/blob/06da19335884759aeb6a2813e627317625a98631/src/main/java/com/moz/qless/Client.java#L57).

**Comment by davidann** [comment]
> I will say it feels a little skeevy to call close on the JedisPool when that argument may be passed in via the constructor of Client.

Agreed.  The `Client` though, clearly wasn't closing anything, so I was dinking around with other ways to close the sockets.

**Comment by b4hand** [comment]
I was saying that if I add a `close` method to `Client` that calling `close` on the `JedisPool` feels skeevy. I think your code above was a reasonable workaround especially if you're already explicitly passing the pool in via the constructor.

The weirdness is due to there being a default constructor that automatically constructs the `JedisPool` for you. In that case, it is clear the `Client` should `close` the `JedisPool` for you since it *owns* the pool, but when you pass the pool in, it would imply that it is the *callers* responsibility to close the pool.

**Comment by b4hand** [comment]
@dlecocq: Dan feels we should just assume ownership of any passed in pool and thinks that we should leave the version of accepting a pool directly because that gives us extra freedom to configure the pool arbitrarily. I'm fine with that as long as it is documented to take ownership.
